services:
  traefik:
    image: traefik:v3.0
    command:
      - "--api.dashboard=true"
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./traefik.yml:/etc/traefik/traefik.yml"

  static:
    image: nginx:latest
    volumes:
      - ./static:/usr/share/nginx/html:ro
    labels:
      - "traefik.http.routers.static.rule=Host(`static.localhost`)"
      - "traefik.http.routers.static.entrypoints=web"
      - "traefik.enable=true"

  php:
    image: php:fpm
    volumes:
      - ./api:/var/www/html

  api:
    image: nginx:latest
    volumes:
      - ./api:/var/www/html
      - ./api/public:/var/www/html/public
      - ./nginx-api.conf:/etc/nginx/conf.d/default.conf
    labels:
      - "traefik.http.routers.api.rule=Host(`api.localhost`)"
      - "traefik.http.routers.api.entrypoints=web"
      - "traefik.enable=true"
    depends_on:
      - php
